### ISSUE TITLE
Run command when mount becomes available

### ISSUE THREAD

**Issue by n-st** [N-Coder/studip-fuse#5]
Enhancement: Add an option to run a command when `studip-fuse` succeeds in mounting.

This would allow the user to correctly automate mounting the FUSE, `rsync`ing files to local storage, and unmounting the FUSE afterwards.

**Comment by N-Coder** [comment]
This could be implemented as last thing to do in the [FUSEView.init](https://github.com/N-Coder/studip-fuse/blob/beta/studip_fuse/__main__/fs_driver.py#L143) method. This would still be *before* the mount actually becomes active, but waiting for 1 second or using a blocking `ls /` should be able to fix that. Nonetheless, that would need some testing regarding timing and edge-cases e.g. when the FUSE driver is shutting down right after having been started.

**Comment by N-Coder** [comment]
There are [multiple](https://stackoverflow.com/questions/4212522/shell-script-to-know-whether-a-filesystem-is-already-mounted) methods for checking for mountpointiness of directories, the best of them is probably the [`mountpoint`](https://linux.die.net/man/1/mountpoint) utility, which also issues a potentially blocking `stat` call. So checking whether the mount is actually available right after the callback should be no problem.

I have a somewhat bad feeling about starting an arbitrary program from within the driver, as this also leads to a lot of security, exception and subprocess handling issues. Would another notification channel also be ok? Busy checking for file / port availability is obviously no perfect solution. Sending a notification via D-Bus would also not present a generic solution, but might be helpful later when it comes to writing an integrated GUI. Another possibility could be `tail`ing the system log and [blockingly searching](https://stackoverflow.com/questions/6454915/linux-block-until-a-string-is-matched-in-a-file-tail-grep-with-blocking) for the respective startup log message, which would also be possible right now without modifications to any studip-fuse code. If you really want an even simpler solution we could also write to a specific normal file on startup (i.e. `echo "started" > /tmp/studip-fuse-%PID.txt`) so that you can just use a blocking read-line to wait for the startup.
